### ISSUE TITLE
Help with installing the plugin

### ISSUE THREAD

**Issue by risjain** [yanick/Taskwarrior-Kusarigami#31]
Hi,

Unable to install the plugin tools. By default, task-kusarigama isn't available upon installing taskwarrior. Can you please add some steps to guide perl-newbies like me - on installing the package from the terminal (or otherwise).

Thanks,

**Comment by yanick** [comment]
Have a look at https://metacpan.org/source/YANICK/Taskwarrior-Kusarigama-0.12.0/INSTALL and let me know if it helps. The tarball itself is available at https://cpan.metacpan.org/authors/id/Y/YA/YANICK/Taskwarrior-Kusarigama-0.12.0.tar.gz

**Comment by risjain** [comment]
Thank you so much - missed that.

**Comment by yanick** [comment]
No problem at all! You have further questions, don't hesitate to poke me. :-)
